name: Python Unit Tests

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: all  # Specify the Python version you want to use
          
      - name: Run unit tests
        run: python -m unittest 

      - name: Upload test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: test-reports  # Adjust the path to your test reports directory
